module.exports = {
  bearerToken: 'Bearer eyJhbGciOiJIUzUxMiIsImV4cCI6MTQ1MTYxNjg4MSwiaWF0IjoxNDQ5MTk3Njc2fQ.eyJ1c2VyX2lkIjoxNywiZW1haWwiOiJwczEwQHN0YWJsZXRva2VuLmNvbSJ9.Ca4suKvQGMzctYGUY6WHWzkcer7K8HTQjie4h0riXBr6_Ns4--UOHsw8hHfrgGjWaT6nttriPOXMvMrCkGkJXg'
}
