module.exports = {
  OwnerBearerToken: 'Bearer 8SXHX0jqRAWs2El7iO86AKsWEyesuy',
  ContributorBearerToken: 'Bearer A5D9D5j556E2378D83799E66AABBA5',
  ManagerBearerToken: 'Bearer ECA4D1462573B21y6961476356E81F',
  JessieBearerToken: 'Bearer PkkG0iGI6I4SZOQ1ora9lnQQu2BwHF',
  CourtneyBearerToken: 'Bearer TfbtVjDNgxhL7HEag8nhzb7WYYEcr9',
  RobBearerToken: 'Bearer YkB9IDhn9kOJsLhNEjiYpFPpufOSgw',
  orderId: 48,
  buy: 1,
  sell: 2,
  unauthorised: 401,
  successfulPost: 201,
  okResponse: 200,
  ownerAuthCode: 'AUTH_CODE_TO_OBTAIN_A_OWNER_TOKEN',
  contributorAuthCode: 'AUTH_CODE_TO_OBTAIN_A_CONTRIBUTOR_TOKEN',
  managerAuthCode: 'AUTH_CODE_TO_OBTAIN_A_MANAGER_TOKEN',
  JessieAuthCode: 'AUTH_CODE_TO_OBTAIN_A_JESSIE_TOKEN',
  CourtneyAuthCode: 'AUTH_CODE_TO_OBTAIN_A_COURTNEY_TOKEN',
  RobAuthCode: 'AUTH_CODE_TO_OBTAIN_A_ROB_TOKEN',
  invalidAuthCode: 'AUTH_CODE_WHICH_IS_INVALID',
  client_id: 'lCVsjCdigGb2khGhX71nREbHZG0ovA5LOiab0bsG',
  client_secret: 'OdKu0czYHGtCwrRRnjM4yeO591dPrMOMTfTWY8yVtKhawpH4IUtUZJ0'
}
